### ISSUE TITLE
master分支，Error: Failed to lookup view "index.hbs" in views directory "/data/github/wewe-rss/apps/server/client"

### ISSUE THREAD

**Issue by gaoyajun01** [cooderl/wewe-rss#147]
.env文件使用mysql数据库，服务启动后，点击wewe-rss链接，报错如下：
`
apps/server dev: prisma:warn Prisma doesn't know which engines to download for the Linux distro "uos". Falling back to Prisma engines built "debian".
apps/server dev: Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
apps/server dev: [Nest] 23228  - 2024/05/23 09:16:08     LOG [NestApplication] Nest application successfully started +270ms
apps/server dev: Server is running at http://0.0.0.0:4000
　apps/server dev: [Nest] 23228  - 2024/05/23 09:16:18   ERROR [ExceptionsHandler] Failed to lookup view "index.hbs" in views directory "/data/github/wewe-rss/apps/server/client"
apps/server dev: Error: Failed to lookup view "index.hbs" in views directory "/data/github/wewe-rss/apps/server/client"
apps/server dev:     at Function.render (/data/github/wewe-rss/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/application.js:597:17)
apps/server dev:     at ServerResponse.render (/data/github/wewe-rss/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/response.js:1039:7)
apps/server dev:     at ExpressAdapter.render (/data/github/wewe-rss/node_modules/.pnpm/@nestjs+platform-express@10.3.3_@nestjs+common@10.3.3_@nestjs+core@10.3.3/node_modules/@nestjs/platform-express/adapters/express-adapter.js:71:25)
apps/server dev:     at RouterResponseController.render (/data/github/wewe-rss/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_@nestjs+platform-express@10.3.3_reflect-metadata@0.2.1_rxjs@7.8.1/node_modules/@nestjs/core/router/router-response-controller.js:29:36)
apps/server dev:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
apps/server dev:     at /data/github/wewe-rss/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_@nestjs+platform-express@10.3.3_reflect-metadata@0.2.1_rxjs@7.8.1/node_modules/@nestjs/core/router/router-execution-context.js:158:24                                                                                                    
apps/server dev:     at /data/github/wewe-rss/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_@nestjs+platform-express@10.3.3_reflect-metadata@0.2.1_rxjs@7.8.1/node_modules/@nestjs/core/router/router-execution-context.js:47:13                                                                                                     
apps/server dev:     at /data/github/wewe-rss/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_@nestjs+platform-express@10.3.3_reflect-metadata@0.2.1_rxjs@7.8.1/node_modules/@nestjs/core/router/router-proxy.js:9:17                                                                                                                  

`

**Comment by xubigshu** [comment]
同样错误，大佬解决了吗？
