### ISSUE TITLE
PrismaClientInitializationError: Server has closed the connection.

### ISSUE THREAD

**Issue by langxuelang** [cooderl/wewe-rss#219]
这两天项目突然报这个错，是在huggingface上部署的。前几天还是好好的。

PrismaClientInitializationError: Server has closed the connection.
    at r (/app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/@prisma/client/runtime/library.js:113:2493)
    at async Proxy.onModuleInit (/app/dist/prisma/prisma.service.js:14:9)
    at async Promise.all (index 0)
    at async callModuleInitHook (/app/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_class-transformer@0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:5)
    at async NestApplication.callInitHook (/app/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_class-transformer@0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm/node_modules/@nestjs/core/nest-application-context.js:223:13)
    at async NestApplication.init (/app/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_class-transformer@0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm/node_modules/@nestjs/core/nest-application.js:100:9)
    at async NestApplication.listen (/app/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_class-transformer@0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm/node_modules/@nestjs/core/nest-application.js:169:33)
    at async bootstrap (/app/dist/main.js:32:5) {
  clientVersion: '5.10.1',
  errorCode: 'P1017'
}

**Comment by langxuelang** [comment]
我自己的数据库出错了
