### ISSUE TITLE
v2.6 更新说明

### ISSUE THREAD

**Issue by cooderl** [cooderl/wewe-rss#320]
v2.6 支持了拉取历史文章，数据库加了一个字段，在更新前可以做一次备份。

**Comment by imrayyu** [comment]
我是用的cooderl/wewe-rss-sqlite:latest镜像，watchtower昨天自动更新的，更新后容器一直在重启无法正常运行。
看了下后台日志，不知道是不是因为这个错误。
PrismaClientInitializationError: Unable to require(`/app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/.prisma/client/libquery_engine-linux-musl.so.node`).
The Prisma engines do not seem to be compatible with your system. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements

Details: Error loading shared library libssl.so.1.1: No such file or directory (needed by /app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/.prisma/client/libquery_engine-linux-musl.so.node)
    at Object.loadLibrary (/app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/@prisma/client/runtime/library.js:112:10151)
    at async vt.loadEngine (/app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/@prisma/client/runtime/library.js:113:448)
    at async vt.instantiateLibrary (/app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/@prisma/client/runtime/library.js:112:12591)
    at async vt.start (/app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/@prisma/client/runtime/library.js:113:1981)
    at async Proxy.onModuleInit (/app/dist/prisma/prisma.service.js:14:9)
    at async Promise.all (index 0)
    at async callModuleInitHook (/app/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_class-transformer@0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:5)
    at async NestApplication.callInitHook (/app/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_class-transformer@0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm/node_modules/@nestjs/core/nest-application-context.js:223:13)
    at async NestApplication.init (/app/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_class-transformer@0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm/node_modules/@nestjs/core/nest-application.js:100:9)
    at async NestApplication.listen (/app/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_class-transformer@0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm/node_modules/@nestjs/core/nest-application.js:169:33) {
  clientVersion: '5.10.1',
  errorCode: undefined
}

**Comment by cooderl** [comment]
> 我是用的cooderl/wewe-rss-sqlite:latest镜像，watchtower昨天自动更新的，更新后容器一直在重启无法正常运行。
> 看了下后台日志，不知道是不是因为这个错误。
> PrismaClientInitializationError: Unable to require(`/app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/.prisma/client/libquery_engine-linux-musl.so.node`).
> The Prisma engines do not seem to be compatible with your system. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements
> 
> Details: Error loading shared library libssl.so.1.1: No such file or directory (needed by /app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/.prisma/client/libquery_engine-linux-musl.so.node)
>     at Object.loadLibrary (/app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/@prisma/client/runtime/library.js:112:10151)
>     at async vt.loadEngine (/app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/@prisma/client/runtime/library.js:113:448)
>     at async vt.instantiateLibrary (/app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/@prisma/client/runtime/library.js:112:12591)
>     at async vt.start (/app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/@prisma/client/runtime/library.js:113:1981)
>     at async Proxy.onModuleInit (/app/dist/prisma/prisma.service.js:14:9)
>     at async Promise.all (index 0)
>     at async callModuleInitHook (/app/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_class-transformer@0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:5)
>     at async NestApplication.callInitHook (/app/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_class-transformer@0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm/node_modules/@nestjs/core/nest-application-context.js:223:13)
>     at async NestApplication.init (/app/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_class-transformer@0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm/node_modules/@nestjs/core/nest-application.js:100:9)
>     at async NestApplication.listen (/app/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_class-transformer@0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm/node_modules/@nestjs/core/nest-application.js:169:33) {
>   clientVersion: '5.10.1',
>   errorCode: undefined
> }

更新到 2.6.1可以解决

**Comment by ziz9** [comment]
你好，huggingface更新2.6.1，发生错误
`runtime error
Exit code: 1. Reason: m. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements

Details: Error loading shared library libssl.so.1.1: No such file or directory (needed by /app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/.prisma/client/libquery_engine-linux-musl.so.node)
    at Object.loadLibrary (/app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/@prisma/client/runtime/library.js:112:10151)
    at async vt.loadEngine (/app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/@prisma/client/runtime/library.js:113:448)
    at async vt.instantiateLibrary (/app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/@prisma/client/runtime/library.js:112:12591)
    at async vt.start (/app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/@prisma/client/runtime/library.js:113:1981)
    at async Proxy.onModuleInit (/app/dist/prisma/prisma.service.js:14:9)
    at async Promise.all (index 0)
    at async callModuleInitHook (/app/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_class-transformer@0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:5)
    at async NestApplication.callInitHook (/app/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_class-transformer@0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm/node_modules/@nestjs/core/nest-application-context.js:223:13)
    at async NestApplication.init (/app/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_class-transformer@0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm/node_modules/@nestjs/core/nest-application.js:100:9)
    at async NestApplication.listen (/app/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_class-transformer@0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm/node_modules/@nestjs/core/nest-application.js:169:33) {
  clientVersion: '5.10.1',
  errorCode: undefined
}

Node.js v20.18.1`

**Comment by cooderl** [comment]
> 大佬您好，huggingface更新2.6.1，发生错误 `runtime error Exit code: 1. Reason: m. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements
> 
> Details: Error loading shared library libssl.so.1.1: No such file or directory (needed by /app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/.prisma/client/libquery_engine-linux-musl.so.node) at Object.loadLibrary (/app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/@prisma/client/runtime/library.js:112:10151) at async vt.loadEngine (/app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/@prisma/client/runtime/library.js:113:448) at async vt.instantiateLibrary (/app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/@prisma/client/runtime/library.js:112:12591) at async vt.start (/app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/@prisma/client/runtime/library.js:113:1981) at async Proxy.onModuleInit (/app/dist/prisma/prisma.service.js:14:9) at async Promise.all (index 0) at async callModuleInitHook (/app/node_modules/.pnpm/@nestjs+core@[10.3.3_@nestjs](mailto:10.3.3_@nestjs)+common@10.3.3_class-transformer@[0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm](mailto:0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm)/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:5) at async NestApplication.callInitHook (/app/node_modules/.pnpm/@nestjs+core@[10.3.3_@nestjs](mailto:10.3.3_@nestjs)+common@10.3.3_class-transformer@[0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm](mailto:0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm)/node_modules/@nestjs/core/nest-application-context.js:223:13) at async NestApplication.init (/app/node_modules/.pnpm/@nestjs+core@[10.3.3_@nestjs](mailto:10.3.3_@nestjs)+common@10.3.3_class-transformer@[0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm](mailto:0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm)/node_modules/@nestjs/core/nest-application.js:100:9) at async NestApplication.listen (/app/node_modules/.pnpm/@nestjs+core@[10.3.3_@nestjs](mailto:10.3.3_@nestjs)+common@10.3.3_class-transformer@[0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm](mailto:0.5.1_class-validator@0.14.1_refl_ogqsyr4bbcztohkf54i7ykqyhm)/node_modules/@nestjs/core/nest-application.js:169:33) { clientVersion: '5.10.1', errorCode: undefined }
> 
> Node.js v20.18.1`

这个看起来还是 2.6.0 。如果用的是 latest标签镜像，可能有缓存，重新部署或者手动改成 2.6.1。可以翻一下这个issue #32

**Comment by candy-frankie** [comment]
大佬你好，我成功部署了最新版2.6.1，不过，点击获取历史文章，只更新了2页就没了，这是什么原因啊？

**Comment by raining1123** [comment]
请问Mysql版和Sqlite版有什么区别？推荐用哪个？
