### ISSUE TITLE
配置为sqlite后启动服务器失败

### ISSUE THREAD

**Issue by eureka176** [cooderl/wewe-rss#39]
在app/server/.env里面配置

DATABASE_URL="file:../data/wewe-rss.db"
DATABASE_TYPE="sqlite"

启动后报错：

PrismaClientInitializationError: error: Error validating datasource `db`: the URL must start with the protocol `mysql://`.
  -->  schema.prisma:3
   | 
 2 |   provider = "mysql"
 3 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
    at r (/home/kali/Downloads/wewe-rss-20240303043604/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/@prisma/client/runtime/library.js:113:2493)
    at async Proxy.onModuleInit (/home/kali/Downloads/wewe-rss-20240303043604/apps/server/dist/prisma/prisma.service.js:14:9)
    at async Promise.all (index 0)
    at async callModuleInitHook (/home/kali/Downloads/wewe-rss-20240303043604/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_@nestjs+platform-express@10.3.3_reflect-metadata@0.2.1_rxjs@7.8.1/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:5)
    at async NestApplication.callInitHook (/home/kali/Downloads/wewe-rss-20240303043604/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_@nestjs+platform-express@10.3.3_reflect-metadata@0.2.1_rxjs@7.8.1/node_modules/@nestjs/core/nest-application-context.js:223:13)
    at async NestApplication.init (/home/kali/Downloads/wewe-rss-20240303043604/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_@nestjs+platform-express@10.3.3_reflect-metadata@0.2.1_rxjs@7.8.1/node_modules/@nestjs/core/nest-application.js:100:9)
    at async NestApplication.listen (/home/kali/Downloads/wewe-rss-20240303043604/node_modules/.pnpm/@nestjs+core@10.3.3_@nestjs+common@10.3.3_@nestjs+platform-express@10.3.3_reflect-metadata@0.2.1_rxjs@7.8.1/node_modules/@nestjs/core/nest-application.js:169:33)
    at async bootstrap (/home/kali/Downloads/wewe-rss-20240303043604/apps/server/dist/main.js:32:5) {
  clientVersion: '5.10.1',
  errorCode: 'P1012'
}

**Comment by gtfvool** [comment]
我也遇到过，看了下Dockerfile发现其中有这么一步
RUN cd /app-sqlite && \
    rm -rf ./prisma && \
    mv prisma-sqlite prisma && \
    pnpm exec prisma generate
我执行了上述命令后就没问题了

**Comment by howie-chen** [comment]
用 Zeabur + sqlite 方案部署，我是 fork 之后用 apps/server/prisma-sqlite 替换 prisma 目录，然后再 deploy。
